### ISSUE TITLE
Getting a "build failed" error when trying to compile downloaded package

### ISSUE THREAD

**Issue by glebgorokhov** [jasonelle/jasonelle#2]
Build fails. I have done nothing more than just downloading the package, opening it in XCode and clicking a "build" button.

I have used this release: https://github.com/jasonelle/jasonelle/releases/tag/v.3.0.1

And this instruction: https://jasonelle.com/docs/xcode/Quickstart.html

![Screenshot 2023-04-19 at 09 53 45](https://user-images.githubusercontent.com/24701608/232990726-1b7ba470-071f-422e-8fe8-27fc6ae08dce.png)

**Comment by clsource** [comment]
I could not replicate the issue.
Please ensure that you are opening **App.xcworkspace** file. 
Thanks :)

**Comment by clsource** [comment]
This maybe related to using M1 (ARM) processors.
Please check https://jasonelle.com/docs/xcode/Quickstart.html#arm-processors-m1-m2

thanks
