### ISSUE TITLE
Android Manifest is failing for Android 12 version onwards

### ISSUE THREAD

**Issue by anibalbastiass** [jasonelle/jasonelle#3]
Hey @clsource 

I'm posting you because I'd like to patch Jasonelle project because you already asked to me how to fix Android Manifest issue below

<img width="300" src="https://github.com/jasonelle/jasonelle/assets/31627741/42123440-3867-4ed6-afb2-2726b49cb1f9">

I'll send a new PR trying to fix and I'll let you know how it goes.

**Comment by anibalbastiass** [comment]
@clsource Waiting my request about to adding me as collaborator to contribute my fix PR

**Comment by clsource** [comment]
Thanks Anibal you are the Goat

**Comment by clsource** [comment]
![telegram-cloud-photo-size-1-4967952452280233035-y](https://github.com/jasonelle/jasonelle/assets/292738/75789482-e944-42f1-a9ad-c593674ab663)
 compiles
